Exercício 01 – Operações com Pandas

a) Abra o arquivo World Happiness.

b) Qual a média do score_felicidade?

c) Qual a soma do PIB?

d) Qual a soma do freedom e corrupção?

e) Há dados duplicados? Quantos? Verifique quais são eles?

In [5]:
# a) Abra o arquivo World Happiness.

import pandas as pd

caminho = './Arquivos/world_happiness_report_2015.csv'

dados = pd.read_csv(caminho)

dados

,country,region,happiness rank,happiness score,standard error,economy (GDP per Capita),family,health (Life Expectancy),freedom,trust (Government Corruption),generosity,dystopia residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...,...
159,Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
160,Benin,Sub-Saharan Africa,155,3.340,NaN,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,NaN
161,Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
162,Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,NaN
163,Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,NaN

In [10]:
mediaFelicidade = dados['happiness score'].mean()

# Tratando a resposta para ter 2 casas decimais
print(f'A média é {mediaFelicidade: .2f}')

A média é  5.42

In [11]:
# MUDANDO A COLUNA economy (GDP per Capita) PARA "PIB"
dados = dados.rename(columns= {'economy (GDP per Capita)':'PIB'})

In [14]:
# c) Qual a soma do PIB?
dados.PIB.sum()

141.37172

In [18]:
# d) Qual a soma do freedom e corrupção?

dados = dados.rename(columns = {'trust (Government Corruption)':'corrupcao'})

dados[['freedom','corrupcao']].sum()

freedom      71.33320
corrupcao    24.59645
dtype: float64

In [21]:
# e) Há dados duplicados? Quantos? Verifique quais são eles?

# Aqui faremos a soma de todos os dados duplicados para assim ele mostrar a quantidade exata de dados duplicados dentro da tabela que neste caso será 6
dados.duplicated().sum()

6

In [22]:
# Aqui será mostrado os 6 dados duplicados conforme mostrado acima
dados[dados.duplicated() == True]

,country,region,happiness rank,happiness score,standard error,PIB,family,health (Life Expectancy),freedom,corrupcao,generosity,dystopia residual
11,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
12,Finland,Western Europe,6,7.406,0.03140,1.29025,1.31826,0.88911,0.64169,0.41372,0.23351,2.61955
13,Netherlands,Western Europe,7,7.378,0.02799,1.32944,1.28017,0.89284,0.61576,0.31814,0.47610,2.46570
14,Sweden,Western Europe,8,7.364,0.03157,1.33171,1.28907,0.91087,0.65980,0.43844,0.36262,2.37119
34,Oman,Middle East and Northern Africa,22,6.853,0.05335,1.36011,1.08182,0.76276,0.63274,0.32524,0.21542,2.47489
35,Venezuela,Latin America and Caribbean,23,6.810,0.06476,1.04424,1.25596,0.72052,0.42908,0.11069,0.05841,3.19131

### Verifique a quantidade de dados faltantes

In [24]:
# Verificar a quantidade de dados faltantes ou nulo, se tiver True é porque há dados faltantes e false é porquê está preenchida

dados.isna().sum()

country                      0
region                       0
happiness rank               0
happiness score              8
standard error               1
PIB                          0
family                       0
health (Life Expectancy)     0
freedom                      0
corrupcao                    0
generosity                   0
dystopia residual           14
dtype: int64

### g) Crie um dataframe onde os valores faltantes de score_felicidade sejam
substituídos por -9999.

In [25]:
dados = dados.fillna(-9999)